[package]
name = "storage"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serialization = { path = "../serialization" }
storage-core = { path = "core" }
utils = { path = "../utils" }
