[package]
name = "utils"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true


[dev-dependencies]
static_assertions.workspace = true

[target.'cfg(loom)'.dependencies]
loom.workspace = true
